# Generated by Django 5.0.7 on 2024-09-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.video'),
        ),
    ]
