# Generated by Django 5.0.7 on 2024-09-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_remove_video_cover_video_course_cover_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='course_photos/'),
        ),
    ]
