# Generated by Django 5.0.7 on 2024-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_alter_course_cover_photo_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
